// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial02;

namespace Parcial02.Migrations
{
    [DbContext(typeof(UCAClinicContext))]
    [Migration("20210526050520_Change01")]
    partial class Change01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Parcial02.Entities.Reservation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("specialityid")
                        .HasColumnType("int");

                    b.Property<int?>("userCardID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("specialityid");

                    b.HasIndex("userCardID");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Parcial02.Entities.SecurityQuestion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("question")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("SecurityQuestions");

                    b.HasData(
                        new
                        {
                            id = 1,
                            question = "What year were you born?"
                        },
                        new
                        {
                            id = 2,
                            question = "What was your first pet's name?"
                        });
                });

            modelBuilder.Entity("Parcial02.Entities.Speciality", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("generalMedicine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("odontology")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ophthalmology")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("psychology")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Specialities");
                });

            modelBuilder.Entity("Parcial02.Entities.User", b =>
                {
                    b.Property<int>("CardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("questionid")
                        .HasColumnType("int");

                    b.HasKey("CardID");

                    b.HasIndex("questionid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Parcial02.Entities.Reservation", b =>
                {
                    b.HasOne("Parcial02.Entities.Speciality", "speciality")
                        .WithMany()
                        .HasForeignKey("specialityid");

                    b.HasOne("Parcial02.Entities.User", "user")
                        .WithMany()
                        .HasForeignKey("userCardID");

                    b.Navigation("speciality");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Parcial02.Entities.User", b =>
                {
                    b.HasOne("Parcial02.Entities.SecurityQuestion", "question")
                        .WithMany()
                        .HasForeignKey("questionid");

                    b.Navigation("question");
                });
#pragma warning restore 612, 618
        }
    }
}
